'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAppDispatch, useAppSelector } from '@/store/hooks';
import { clearCart } from '@/store/slices/cart-slice';
const money = new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN', maximumFractionDigits: 0 });
export function Checkout() { const items = useAppSelector(s => s.cart.items); const total = useAppSelector(s => s.cart.items.reduce((sum, item) => sum + item.price * item.quantity, 0)); const { user, hydrated } = useAppSelector(s => s.auth); const addresses = useAppSelector(s => s.addresses.items); const selectedId = useAppSelector(s => s.addresses.selectedId); const dispatch = useAppDispatch(); const router = useRouter(); const [finished, setFinished] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const number = 'LM-' + String(10482 + items.length);
  useEffect(() => { if (hydrated && !user) router.replace('/acceso?regresar=/checkout'); }, [hydrated, user, router]);
  if (!hydrated || !user) return <section className="form-page"><div className="form-card"><h1>Verificando tu sesión…</h1></div></section>;
  if (!items.length && !finished) return <section className="form-page"><div className="form-card"><h1>No hay productos para pagar</h1><Link className="button" href="/productos">Ir al catálogo</Link></div></section>;
  if (finished) return <section className="form-page"><div className="form-card success"><p className="eyebrow">PEDIDO CONFIRMADO</p><h1>¡Gracias por tu compra!</h1><p>Tu pago de prueba fue autorizado. Conserva este número para consultar el estado.</p><strong>{number}</strong><Link className="button full" href={'/pedido?numero=' + number}>Rastrear mi pedido</Link></div></section>;
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedId) return setError('Selecciona o agrega una dirección de entrega antes de pagar.'); const data = new FormData(event.currentTarget); const card = String(data.get('card')).replace(/\s/g, ''); const expiry = String(data.get('expiry')); const cvv = String(data.get('cvv')); if (!/^\d{13,19}$/.test(card)) return setError('Ingresa un número de tarjeta válido.'); if (!/^\d{2}\/\d{2}$/.test(expiry) || !/^\d{3,4}$/.test(cvv)) return setError('Revisa el vencimiento y el CVV.'); setError(''); setLoading(true); window.setTimeout(() => { dispatch(clearCart()); setLoading(false); setFinished(true); }, 700); };
  return <section className="checkout"><div><p className="eyebrow">FINALIZAR COMPRA</p><h1>Datos de entrega</h1><p>Compra como <b>{user.email}</b>.</p><div className="delivery-choice"><b>Dirección seleccionada</b>{addresses.filter(a => a.id === selectedId).map(a => <span key={a.id}>{a.recipient} · {a.line1}, {a.city} C.P. {a.postalCode}</span>)}<Link href="/direcciones">{selectedId ? 'Cambiar dirección' : 'Agregar dirección'}</Link></div><form onSubmit={submit}><h2>Pago simulado</h2><div className="payment-note">?? No se procesa ningún cargo. Este formulario simula la respuesta de una pasarela de pago.</div><label>Número de tarjeta<input name="card" required inputMode="numeric" placeholder="4242 4242 4242 4242" /></label><div className="two-cols"><label>Vencimiento<input name="expiry" required placeholder="MM/AA" /></label><label>CVV<input name="cvv" required inputMode="numeric" placeholder="123" /></label></div>{error && <p className="field-error">{error}</p>}<button className="button full" disabled={loading}>{loading ? 'Procesando…' : 'Confirmar pedido'}</button></form></div><aside className="summary"><h2>Tu pedido</h2>{items.map(x => <div key={x.id}><span>{x.name} × {x.quantity}</span><span>{money.format(x.price * x.quantity)}</span></div>)}<hr /><div className="total"><b>Total</b><b>{money.format(total)}</b></div></aside></section>; }
